apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-artist
  description: Artist main website
  annotations:
    gitInsights/project-key: gitInsights/backstage-plugin-git-insights-sample
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
